#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd org.idempiere.prueba.targetplatform
./plugin-builder $DEBUG_MODE ../org.idempiere.prueba ../org.idempiere.prueba.test
