#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd org.plugin.prueba.targetplatform
./plugin-builder $DEBUG_MODE ../org.plugin.prueba ../org.plugin.prueba.test
